{"uuid": "d19de088-3f69-499b-abe3-9ba7a5199664", "children": ["deda43f2-cdd0-41ec-a3d3-623df1c2a9ba"], "befores": [{"name": "fp_idSet", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"c:\\python3.8\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\MyProject\\Api-test\\TestCase\\conftest.py\", line 226, in fp_idSet\n    return response['responseData']['data'][0]['fpId']\n"}, "start": 1602663249208, "stop": 1602663249552}], "start": 1602663249208, "stop": 1602663249583}