{"uuid": "868e1b1a-aa4b-4108-8c6f-bbb38daf51f4", "children": ["a12aa8a9-8cbf-42c9-bdd3-72eff9ec45cc"], "befores": [{"name": "fp_idSet", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"c:\\python3.8\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\MyProject\\Api-test\\TestCase\\conftest.py\", line 226, in fp_idSet\n    return response['responseData']['data'][0]['fpId']\n"}, "start": 1602663257240, "stop": 1602663257834}], "start": 1602663257240, "stop": 1602663257849}